// app/algorithm-practice.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { Algorithm, AlgorithmType } from './algorithm';
import { Database } from './database.service';

import { AlgorithmComponent } from './algorithm.component';

enum State {
    Unitialized,
    Idle,
    Countdown,
    Running
}

@Component({
    selector: 'algorithm-practice',
    templateUrl: 'app/algorithm-practice.component.html',
    directives: [AlgorithmComponent],
    host: {
        '(document:keydown)': 'keydown($event)'
    }
})
export class AlgorithmPracticeComponent implements OnInit {
    @Input()
    algorithmType: AlgorithmType;

    algorithms: Algorithm[];

    currentAlgorithm: Algorithm;
    displayValue = "ready";
    showAlgorithm = false;

    private state = State.Unitialized;
    private startTime;
    private interval;

    constructor(private database: Database) { }

    ngOnInit() {
        this.database.getAlgorithms().then(
            algorithms => {
                this.algorithms = algorithms.filter(
                    x => x.type == this.algorithmType);

                this.initialize();
            });
    }

    private initialize() {
        this.state = State.Idle;
    }

    private keydown(event: KeyboardEvent) {
        if (event.keyCode == 32) {
            switch (this.state) {
            case State.Idle:
                this.state = State.Countdown;
                this.currentAlgorithm = null;
                this.showAlgorithm = false;
                this.displayValue = "3";
                setTimeout(() => {
                    this.displayValue = "2";
                    setTimeout(() => {
                        this.currentAlgorithm = this.algorithms[Math.floor(Math.random() * this.algorithms.length)];
                        this.displayValue = "1";
                        setTimeout(() => {
                            this.state = State.Running;
                            this.startTime = Date.now();
                            this.interval = setInterval(() => {
                                let elapsed = new Date(Date.now() - this.startTime);
                                this.displayValue = elapsed.getSeconds() + "." + elapsed.getMilliseconds();
                            }, 0);
                        }, 1000);
                    }, 1000);
                }, 1000);
                break;

            case State.Running:
                this.state = State.Idle;
                clearInterval(this.interval);
                this.showAlgorithm = true;
                break;
            }
        }
    }
}

// src/components/AlgorithmPractice.vue
<template>
  <div v-show="show">
    <div class="row">
      <div class="twelve columns">
        <div align="center">
          <img v-if="currentAlgorithm" style="display: inline-block; width: 228px; height: 228px" :src="'static/' + currentAlgorithm.imageFileName" />
          <div v-if="!currentAlgorithm" style="display: inline-block; width: 228px; height: 228px"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="twelve columns">
        <div align="center">
          <h4>{{displayText}}</h4>
        </div>

        <algorithm v-if="showAlgorithm" :algorithm="currentAlgorithm"></algorithm>
      </div>
    </div>
  </div>
</template>

<script>
import algorithms from "../algorithms"
import Algorithm from "./Algorithm"

// Makeshift enum :)
const idle = 1;
const countdown = 2;
const running = 3;

export default {
  components: {
    Algorithm
  },
  props: ["algorithmType", "show"],
  data() {
    return {
      currentAlgorithm: null,
      displayText: "ready",
      showAlgorithm: false,

      state: idle,
      startTime: 0,
      interval: 0
    }
  },
  computed: {
    algorithms() {
      return algorithms.filter(x => x.type == this.algorithmType);
    }
  },
  methods: {
    space() {
      const self = this;

      switch (self.state) {
        case idle:
          self.state = countdown;
          self.currentAlgorithm = null;
          self.showAlgorithm = false;
          self.displayText = "3";
          setTimeout(() => {
            self.displayText = "2";
            setTimeout(() => {
              self.currentAlgorithm = self.algorithms[Math.floor(Math.random() * self.algorithms.length)];
              self.displayText = "1";
              setTimeout(() => {
                self.state = running;
                self.startTime = Date.now();
                self.interval = setInterval(() => {
                  const elapsed = new Date(Date.now() - self.startTime);
                  self.displayText = elapsed.getSeconds() + "." + elapsed.getMilliseconds();
                }, 0);
              }, 1000);
            }, 1000);
          }, 1000);
          break;

        case running:
          self.state = idle;
          clearInterval(self.interval);
          self.showAlgorithm = true;
          break;
      }
    },
    keydown(e) {
      if (e.keyCode === 32) {
        this.space();
      }
    }
  },
  watch: {
    "show": function(val, oldVal) {
      if (val === oldVal) {
        return;
      }

      if (val) {
        window.addEventListener("keydown", this.keydown);
      } else {
        window.removeEventListener("keydown", this.keydown);
      }
    }
  }
}
</script>
