// app/app.component.ts
import { Component } from '@angular/core';
// TODO: Look into why this is deprecated and what to use instead
import { RouteConfig, ROUTER_DIRECTIVES, ROUTER_PROVIDERS } from '@angular/router-deprecated';

import { Database } from './database.service';

import { SolvingComponent } from './solving.component';
import { OllPracticeComponent } from './oll-practice.component';
import { PllPracticeComponent } from './pll-practice.component';
import { AlgorithmsComponent } from './algorithms.component';

@Component({
    selector: 'my-app',
    templateUrl: 'app/app.component.html',
    directives: [ROUTER_DIRECTIVES],
    providers: [
        ROUTER_PROVIDERS,
        Database
    ]
})
@RouteConfig([
    {
        path: '/solving',
        name: 'Solving',
        component: SolvingComponent,
        useAsDefault: true
    },
    {
        path: '/oll-practice',
        name: 'OllPractice',
        component: OllPracticeComponent
    },
    {
        path: '/pll-practice',
        name: 'PllPractice',
        component: PllPracticeComponent
    },
    {
        path: '/algorithms',
        name: 'Algorithms',
        component: AlgorithmsComponent
    }
])
export class AppComponent {
    title = 'assistant';
}

<div class="container">
  <div class="row" style="margin-top: 10%">
    <div class="one column">
      <img src="images/kurisu.gif" />
    </div>

    <div class="eleven columns">
      <h1>{{title}}</h1>
    </div>
  </div>

  <hr />

  <div class="row">
    <div class="twelve columns">
      <a class="button button-primary" [routerLink]="['Solving']">standard solving</a>
      <a class="button button-primary" [routerLink]="['OllPractice']">oll practice</a>
      <a class="button button-primary" [routerLink]="['PllPractice']">pll practice</a>
      <a class="button button-primary" [routerLink]="['Algorithms']">algorithms</a>
    </div>
  </div>

  <hr />

  <router-outlet></router-outlet>
</div>

// src/App.vue
<template>
  <div class="container">
    <div class="row" style="margin-top: 10%">
      <div class="one column">
        <img src="./assets/kurisu.gif">
      </div>

      <div class="eleven columns">
        <h1>assistant</h1>
      </div>
    </div>

    <hr />

    <div class="row">
      <div class="twelve columns">
        <a class="button">standard solving</a>
        <a class="button button-primary" href="#">oll practice</a>
        <a class="button button-primary" href="#">pll practice</a>
        <a class="button button-primary" v-link="{ path: '/algorithms' }">algorithms</a>
      </div>
    </div>

    <hr />

    <router-view></router-view>
  </div>
</template>

<script>
import Algorithms from './components/Algorithms'

export default {
  components: {
    Algorithms
  }
}
</script>

<style src="./assets/skeleton.css"></style>
